name: ci
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        rust-version: ["1.81.0"]
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            rust-version: stable
    name: ${{ matrix.os }} - ${{ matrix.rust-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install (Dependencies)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libwebkit2gtk-4.1-dev libxdo-dev libjavascriptcoregtk-4.1-dev
      - name: Install (Rust)
        run: |
          rustup toolchain install ${{ matrix.rust-version }} --profile default --no-self-update
          rustup default ${{ matrix.rust-version }}
          cargo --version
      - name: Cache (Rust)
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install (Dioxus)
        run: |
          cargo install --locked dioxus-cli@0.5.7
      - name: Lint
        if: matrix.rust-version != 'stable'
        run: |
          echo ::group::dx
          dx fmt --check
          echo ::endgroup::
          echo ::group::rustfmt
          cargo fmt --check
          echo ::endgroup::
          echo ::group::clippy
          cargo clippy --locked -- -Dwarnings
          echo ::endgroup::
      - name: Build (Desktop)
        env:
          RUSTFLAGS: "-Dwarnings"
        run: |
          cargo build --locked
      - name: Build (Web)
        env:
          RUSTFLAGS: "-Dwarnings"
        run: |
          dx build -- --no-default-features --features=web
